# Generated by Django 4.2.11 on 2024-03-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadenaDeCustodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcadena', models.CharField(help_text='Identificador de cadena de custodia)', max_length=20, verbose_name='PM')),
                ('cliente', models.CharField(max_length=45)),
                ('proyecto', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=45)),
                ('muestreado_por', models.CharField(max_length=45)),
                ('punto_de_muestreo', models.CharField(max_length=45)),
                ('coordenada_norte', models.CharField(max_length=45)),
                ('coordenada_este', models.CharField(max_length=45)),
                ('altura', models.FloatField()),
                ('observaciones', models.TextField(help_text='Ingrese una breve descripción de la toma de muestras', max_length=1000)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('simbolo', models.CharField(max_length=45)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('pmolecular', models.FloatField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamedicion', models.DateField()),
                ('hora', models.TimeField()),
                ('resultado', models.FloatField(default=0)),
                ('resultado_conversion', models.FloatField(default=1, editable=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('cadena_custodia', models.ForeignKey(default=1, help_text='Seleccionar cadena de custodia', on_delete=django.db.models.deletion.RESTRICT, to='LimsAire.cadenadecustodia')),
                ('parametro', models.ForeignKey(default=1, help_text='Seleccionar parametro', on_delete=django.db.models.deletion.RESTRICT, to='LimsAire.parametros')),
                ('unidad_de_conversion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='unidad_de_conversion', to='LimsAire.unidaddemedicion')),
                ('unidad_de_medida', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='unidad_de_medicion', to='LimsAire.unidaddemedicion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactorDeConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(default=1)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='LimsAire.parametros')),
                ('unidad_destino', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='unidad_destino', to='LimsAire.unidaddemedicion')),
                ('unidad_origen', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='unidad_origen', to='LimsAire.unidaddemedicion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cadenadecustodia',
            name='parametro',
            field=models.ManyToManyField(help_text='Seleccionar parámetro', to='LimsAire.parametros'),
        ),
        migrations.AddField(
            model_name='cadenadecustodia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
