# Generated by Django 4.2.11 on 2024-03-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LimsAire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factordeconversion',
            old_name='parametros',
            new_name='parametro',
        ),
    ]
