# Generated by Django 4.2.11 on 2024-03-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LimsAire', '0002_rename_parametros_factordeconversion_parametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenadecustodia',
            name='idcadena',
            field=models.CharField(max_length=20, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='cadenadecustodia',
            name='observaciones',
            field=models.TextField(max_length=1000),
        ),
    ]
